#!/usr/bin/env bash

: <<!
Name: terminal-time
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:53:29

Description: 对终端操作进行录屏

Attentions:
- 文件存储位置："$HOME/Documents/AppCache/terminal-time/"

Depends:
- util-linux
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Parameter Variable
# path variable
readonly timefile="$HOME/Documents/AppCache/terminal-time/Terminal-Time.time"
readonly txtfile="$HOME/Documents/AppCache/terminal-time/Terminal-Time.txt"

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ls "$timefile" &>/dev/null && rm "$timefile"
ls "$txtfile" &>/dev/null && rm "$txtfile"

echo -e "\\e[1;34mFlash Start:\\e[0m"
script -t -a "$txtfile" 2>"$timefile"
echo -e "\n\\e[35mFlash Stop\\e[0m"
