#!/usr/bin/env bash

: <<!
Name: benchmarker
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:35:24

Description: 设备性能测试程序

Attentions:
-

Depends:
- hdparm

TODO List:
- TODO(2020-06-19 17:37)：添加设备检测，自动检测是HDD还是SSD
- TODO(2020-07-22 18:59)：添加其他设备的测试
!

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
hdparm -Tt --direct /dev/nvme*
