#!/usr/bin/env bash

: <<!
Name: backup-sddm-theme
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 10:57:48

Description: 备份sddm的主题文件

Attentions:
- 拒绝在root权限下执行

Depends:
- tar
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Exit Code Variable
readonly err_file=1         # 文件/路径类错误
readonly err_permission=110 # 权限错误

#------------------------- Parameter Variable
# path variable
readonly themepath="/usr/share/sddm/themes"
readonly backupdir="$HOME/Documents/MyRepos/System-Conf/confile/usr/sddm"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Feature Function
function checkUser() {
  if [[ $USER == "$1" ]]; then
    echo -e "\n\\e[31m[✘]\\e[0m 当前用户是$1，拒绝执行！！！"
    exit $err_permission
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
checkUser "root"

if [[ -d $backupdir ]]; then
  # sddm-themes
  cd "$backupdir" || exit $err_file
  cp -r "$themepath" "$backupdir" && tar -czv --file="$PWD/themes.tgz" ./themes && rm -r "$PWD/themes"
  echo -e "\nsddm Theme备份完成\n"
else
  mkdir -p "$backupdir"
  # sddm-themes
  cp -r "$themepath" "$backupdir" && tar -czv --file="$PWD/themes.tgz" ./themes && rm -r "$PWD/themes"
  echo -e "\nsddm Theme备份完成\n"
fi

echo -e "备份文件夹: $backupdir\n"
