#!/usr/bin/env bash

: <<!
Name: polybar-script_uptime-info
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-02-13 10:07:54

Description: 系统已启动时间

Attentions:
-

Depends:
-
!

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
uptime --pretty | sed 's/up //' | sed 's/\ years\?,/y/' | sed 's/\ weeks\?,/w/' | sed 's/\ days\?,/d/' | sed 's/\ hours\?,\?/h/' | sed 's/\ minutes\?/m/'
