#!/usr/bin/env bash

: <<!
Name: system-slim
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:52:22

Description: 系统瘦身，清理孤立的软件包

Attentions:
- lonely_pkgs变量不能加引号

Depends:
- pacman
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Parameter Variable
# detection variable
readonly lonely_pkgs=$(pacman -Qtdq)

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
if [[ -z $lonely_pkgs ]]; then
  echo -e "\\e[35m[✔]\\e[0m 没有需要清理的包"
else
  pkexec pacman -Rn $lonely_pkgs # 不能使用引号
fi
