# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME=powerlevel10k/powerlevel10k      # 快、安装时选择配置、美观
# ZSH_THEME="bullet-train"                   # 简洁、慢
# ZSH_THEME="agnoster"                       # 默认

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"
setopt HIST_IGNORE_DUPS

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git                       # 提供git命令的alias
  golang                    # 提供go命令的alias
  docker                    # docker命令自动补全
  extract                   # 文件解压缩
  docker-compose            # docker-compose命令自动补全和alias
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"


# -------------------------------- Bash origin setting -------------------------------- #
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'


# -------------------------------- MySettings -------------------------------- #
# --加载zsh插件
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
source /usr/share/doc/pkgfile/command-not-found.zsh

# --避免手动重置终端
ttyctl -f

# --about virtualenv
virtualenv="/usr/bin/virtualenv"
python="/usr/bin/python"
workon_home="/home/yj/.virtualenvs"
virtualenvwrapper="/usr/bin/virtualenvwrapper.sh"
virtualenvwrapper_lazy="/usr/bin/virtualenvwrapper_lazy.sh"
if [[ -x $virtualenv && -x $python ]]; then
  if [[ ! -d $workon_home ]]; then
    mkdir "$workon_home"
  fi
  export WORKON_HOME="$workon_home"
  if [[ -s $virtualenvwrapper_lazy ]]; then
    . "$virtualenvwrapper_lazy"
  else
    . "$virtualenvwrapper"
  fi
  export VIRTUALENVWRAPPER_PYTHON="$python"
fi

# --about pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PYTHON_CONFIGURE_OPTS="--enable-shared"

# --about Command 'fuck'
eval $(thefuck --alias)

# --about Command 'dtags'
command -v dtags-activate > /dev/null 2>&1 && eval "`dtags-activate zsh`"

# --about http/https proxy
export http_proxy="http://127.0.0.1:1080"
export https_proxy=$http_proxy
alias on="export http_proxy=http://127.0.0.1:1080 https_proxy=$http_proxy"
alias off="unset http_proxy https_proxy"

# --about alias
alias g-a='git status && git add . && git commit -am '
alias ll='exa -lhiFgHS'
alias lla='exa -alhiFgHS'
alias llt='exa -lhiFgHST'
alias llat='exa -alhiFgHST'
alias cp='cp -irv'
alias pbcopy='xsel --clipboard --input'     # 复制终端输出到剪切板
alias pbpaste='xsel --clipboard --output'   # 粘贴剪切板内容到终端
alias rm='trash-put'                        # 屏蔽rm
alias vi='nvim'                             # 屏蔽vi
alias emacs='emacs -nw'                     # 以文本模式启动emacs
alias ml='apropos'                          # 检索命令
alias img='feh -F --auto-zoom'              # 查看图片
alias 2ipython='workon 2 && ipython'        # 一键开启env3及其ipython
alias 3ipython='workon 3 && ipython'        # 一键开启env2及其ipython
alias diff='colordiff'                      # diff着色
alias lsb_release='lsb_release -a'          # 显示系统信息
alias todo='nvim TODO.todo.md'              # 快速打开TODO文件
alias me='nvim README.md'                   # 快速打开README文件
alias ydcv='off && ydcv'                    # 打开ydcv词典
# --使用指定命令打开指定后缀的文件
alias -s {conf,hook,dbc,toml,yaml,json,xml,txt,go,rs,nim}=nvim
alias -s {md,mkd,mkdn,mdwn,mdown,markdown}=typora
alias -s {png,PNG,jpg,JPG,jpeg,JPEG}=img
alias -s {mp4,avi,flv}=mpv
alias -s {pdf,PDF}=xreader
alias -s {chm,CHM}=xchm
alias -s {doc,docx}=wps
alias -s {ppt,pptx}=wpp
alias -s {xls,xlsx,csv}=et

# --当安装/卸载包时zsh通过hook自动刷新PATH变量
zshcache_time="$(date +%s%N)"               # 按需rehash
autoload -Uz add-zsh-hook
rehash_precmd() {
  if [[ -a /var/cache/zsh/pacman ]]; then
    local paccache_time="$(date -r /var/cache/zsh/pacman +%s%N)"
    if (( zshcache_time < paccache_time )); then
      rehash
      zshcache_time="$paccache_time"
    fi
  fi
}
add-zsh-hook -Uz precmd rehash_precmd

# --设置session之间共享history记录
setopt share_history

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# --初始化pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
